# -*- coding: utf-8 -*-
"""DL1_k.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KZCa_QdSRPWwWkX3lmxFOE43YwOcTUOc
"""

import numpy as np
import pandas as pd

data = pd.read_csv("/content/HousingData.csv");

data.head()

data.describe()

data.ffill(inplace = True)
data.isna().sum()

from sklearn.model_selection import train_test_split
x = data.drop("MEDV",axis = 1)
y = data["MEDV"]
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size = 0.8,random_state = 1)

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(1,activation = 'linear'))
model.compile(optimizer = 'adam',loss = 'mse',metrics = ['mae','mse'])

history = model.fit(x_train,y_train,epochs = 150)

model.summary()

metrics = model.evaluate(x_test,y_test)

